export const RoutePaths = {
  ROOT: "/",
  LOG_IN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  CREATE_PRODUCTS: "/create-product",
  EDIT_PRODUCT: "/product/:id/edit",
  CATEGORIES: "/categories",
  CREATE_CATEGORY: "/create-category",
  EDIT_CATEGORY: "/category/:id/edit",
  CONFIRM_EMAIL: "/confirm-email",
  REGISTERATION_COMPLETE: "/registeration-complete",
  CUSTOMERS: "/customers",
  NEW_CUSTOMER: "/customers/new",
  KNOWLEDGE_BASE: "/knowledge-base",
  PERSONAL_SETTINGS: "/settings/personal",
};
