export const RoutePaths = {
  ROOT: "/",
  LOG_IN: "/auth/login",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  DASHBOARD: "/dashboard",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  CREATE_PRODUCTS: "/products/create",
  ADD_PRODUCTS: "/products/create/:id",
  EDIT_PRODUCT: "/product/:id/:productName/edit",
  CATEGORIES: "/categories",
  CREATE_CATEGORY: "/create-category",
  EDIT_CATEGORY: "/categories/:id",
  CONFIRM_EMAIL: "/auth/confirm-email",
  REGISTRATION_COMPLETE: "/auth/registration-complete",
  CUSTOMERS: "/customers",
  NEW_CUSTOMER: "/customers/create",
  EDIT_CUSTOMER: "/customers/edit",
  COUPONS: "/coupons",
  NEW_COUPON: "/coupons/create",
  EDIT_COUPON: "/coupons/edit",
  KNOWLEDGE_BASE: "/knowledge-base",
  PERSONAL_SETTINGS: "/settings/personal",
  GLOBAL_SETTINGS: "/global-settings",
};
