export const RoutePaths = {
  ROOT: "/",
  LOG_IN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  CREATE_PRODUCTS: "/products/create",
  EDIT_PRODUCT: "/product/:id/edit",
  CATEGORIES: "/categories",
  CREATE_CATEGORY: "/create-category",
  EDIT_CATEGORY: "/categories/:id",
  CONFIRM_EMAIL: "/confirm-email",
  REGISTERATION_COMPLETE: "/registeration-complete",
  CUSTOMERS: "/customers",
  NEW_CUSTOMER: "/customers/create",
  EDIT_CUSTOMER: "/customers/edit",
  COUPONS: "/coupons",
  NEW_COUPON: "/coupons/create",
  EDIT_COUPON: "/coupons/edit",
  KNOWLEDGE_BASE: "/knowledge-base",
  PERSONAL_SETTINGS: "/settings/personal",
  GLOBAL_SETTINGS: "/global-settings",
};
